#' @export
ComboQueries <- list(
  last_filled = "last_filled",
  staff_file = "staff_file",
  all_positions_budget = "all_positions_budget"
)

#' Execute Complex Table Queries
#'
#' @param query_name The name of the query to execute. Type 'ComboQueries$' and press TAB to see available queries
#' @return A dataframe containing the query results
#' @examples
#' \dontrun{
#' # Type ComboQueries$ and press TAB to see available queries
#' data <- comboTable(ComboQueries$last_filled)
#' }
#' @export
comboTable <- function(query_name) {
  if (!exists("hr_domino")) {
    hr_domino_connect()
  }
  
  # Query definitions
  queries <- list(
    last_filled = function() {
      # Create the SQL query directly
      query <- "
                SELECT POSTL4.POS_NUM_CD, ASSIGNMENTS_ALL_V.EAS_END_DTE
                FROM S1025879.HRMSLEA.ASSIGNMENTS_ALL_V ASSIGNMENTS_ALL_V, 
                     S1025879.HRMSGCS.POSTL4 POSTL4
                WHERE ASSIGNMENTS_ALL_V.EAS_POS_DOCID = POSTL4.POS_DOCID 
                AND ((ASSIGNMENTS_ALL_V.SOURCE='A'))
                ORDER BY ASSIGNMENTS_ALL_V.EAS_END_DTE DESC
            "
      
      result <- DBI::dbGetQuery(hr_domino, query)
      return(result)
    },
    staff_file = function() {
    query <- "
    SELECT POSITION_VW.POS_NUMBER, POSITION_VW.DESCRIPTION, ASSIGNMENT_VIEW.CATEGORY, POSITION_VW.SITE, SITE.STE_SITE_NM, SITE.STE_TYPE_CD, ASSIGNMENT_VIEW.FIRSTNAME, EMPLOYEE.EMP_MIDDLE_NM, ASSIGNMENT_VIEW.LASTNAME, EMPLOYEE.EMP_SSN_TXT, POSITION_VW.POS_TERM, POSITION_VW.POS_FUNDED_PCT, ASSIGNMENT_VIEW.ASSIGN_PRIMARY, EMPLOYEE.EMP_STATUS_CD, EMPLOYMENT_STATUS_DOM.ESTD_DESC, EMPLOYEE.EMP_RETIREMENT_ID, ASSIGNMENT_VIEW.BIRTHDATE, EMPLOYEE.EMP_ETHNIC_CD, RACE_FLAT_V.RACELIST, EMPLOYEE.EMP_GENDER_CD, ASSIGNMENT_VIEW.ASSIGN_GRADE, ASSIGNMENT_VIEW.ASSIGN_STEP, EMPLOYEE.EMP_ORIGHIRE_DTE, ASSIGNMENT_VIEW.LASTHIRE, ASSIGNMENT_VIEW.LONGEVITY_DATE, POSITION_VW.POS_SAL_SCHEDD, POSITION_VW.PAYMETHOD, POSITION_VW.POS_STATUS, ASSIGNMENT_VIEW.ASSIGN_START, ASSIGNMENT_VIEW.ASSIGN_END, POSITION_VW.FULLORPARTTIME, ASSIGNMENT_VIEW.BT_STATUS, TENURE_STATUS_DOM.CSTD_DESC, EMPLOYEE.EMP_PBL_CMPLT_DTE, EMPLOYEE.EMP_STREET_AD, EMPLOYEE.EMP_CITY_AD, EMPLOYEE.EMP_STATE_AD, EMPLOYEE.EMP_ZIP_AD, EMPLOYEE.EMP_HPHONE_AD, POSITION_VW.EE05, POSITION_VW.SS220, POSITION_VW.SS300, POSITION_VW.SS510, EMP_LOCAL_USE_ANSWER.EMPA_ANSWER, POSITION_WITH_LOCAL_USE_V.POS_STDHRS_NUM
FROM S1025879.HRMSGCS.ASSIGNMENT_VIEW ASSIGNMENT_VIEW, S1025879.HRMSLEA.EMP_LOCAL_USE_ANSWER EMP_LOCAL_USE_ANSWER, S1025879.HRMSLEA.EMPLOYEE EMPLOYEE, S1025879.HRMSSHR.EMPLOYMENT_STATUS_DOM EMPLOYMENT_STATUS_DOM, S1025879.HRMSLEA.POSITION_VW POSITION_VW, S1025879.HRMSLEA.POSITION_WITH_LOCAL_USE_V POSITION_WITH_LOCAL_USE_V, S1025879.HRMSLEA.RACE_FLAT_V RACE_FLAT_V, S1025879.HRMSSHR.SITE SITE, S1025879.HRMSSHR.TENURE_STATUS_DOM TENURE_STATUS_DOM
WHERE ASSIGNMENT_VIEW.POS_NUMBER = POSITION_VW.POS_NUMBER AND EMPLOYEE.EMP_SSN_TXT = ASSIGNMENT_VIEW.SSN AND POSITION_VW.SITE = SITE.STE_SITE_CD AND EMPLOYEE.EMP_STATUS_CD = EMPLOYMENT_STATUS_DOM.ESTD_ID AND EMPLOYEE.EMP_SSN_TXT = EMP_LOCAL_USE_ANSWER.EMPA_EMP_SSN_TXT AND EMPLOYEE.EMP_SSN_TXT = RACE_FLAT_V.ER_SSN_TXT AND POSITION_VW.POS_NUMBER = POSITION_WITH_LOCAL_USE_V.POS_NUM_CD AND EMPLOYEE.EMP_TENURE_STS_CD = TENURE_STATUS_DOM.CSTD_ID AND ((EMP_LOCAL_USE_ANSWER.EMPA_EMPQ_ID=1))
    "
    result <- DBI::dbGetQuery(hr_domino, query)
    return(result)
    },
    all_positions_budget = function() {
      query <- "
    SELECT ALL_POS_CUR_AND_FUT_VW.POS_SITE_CD, ALL_POS_CUR_AND_FUT_VW.STE_TYPE_CD, ALL_POS_CUR_AND_FUT_VW.STE_SITE_NM, ALL_POS_CUR_AND_FUT_VW.POS_NUM_CD, ALL_POS_CUR_AND_FUT_VW.POS_DESC, ALL_POS_CUR_AND_FUT_VW.POS_CATEGORY_CD, ALL_POS_CUR_AND_FUT_VW.POS_STATUS_CD, ALL_POS_CUR_AND_FUT_VW.POS_TERM_NUM, ALL_POS_CUR_AND_FUT_VW.POS_FUNDED_PCT, ALL_POS_CUR_AND_FUT_VW.POS_GRADE_CD, ALL_POS_CUR_AND_FUT_VW.CUR_EAS_GRADE_CD, ALL_POS_CUR_AND_FUT_VW.CUR_EAS_STEP_CD, ALL_POS_CUR_AND_FUT_VW.CUR_EAS_EMPLD_PCT, ALL_POS_CUR_AND_FUT_VW.CUR_EAS_START_DTE, ALL_POS_CUR_AND_FUT_VW.CUR_EAS_END_DTE, ALL_POS_CUR_AND_FUT_VW.EMP_STATUS_CD, ALL_POS_CUR_AND_FUT_VW.ESTD_DESC, ALL_POS_CUR_AND_FUT_VW.EMP_FIRST_NM, ALL_POS_CUR_AND_FUT_VW.EMP_LAST_NM, POSBDCDGCS.FUND, POSBDCDGCS.PURPOSE, POSBDCDGCS.PRC, POSBDCDGCS.OBJ, POSBDCDGCS.LOCALCODE, POSBDCDGCS.DEPT, POSBDCDGCS.PBC_EMPL_PCT, ALL_POS_CUR_AND_FUT_VW.FUT_EAS_START_DTE, ALL_POS_CUR_AND_FUT_VW.FUT_FIRST_NM, ALL_POS_CUR_AND_FUT_VW.FUT_EMP_LAST_NM, POSBDCDGCS.POS_START_DTE, POSBDCDGCS.POS_END_DATE, ALL_POS_CUR_AND_FUT_VW.CUR_SSN_TXT, POSBDCDGCS.PBC_HOURS_NUM, POSBDCDGCS.POS_PAYMTHD_CD, POSBDCDGCS.POS_HOURS_NUM, ALL_POS_CUR_AND_FUT_VW.CUR_EAS_HOURS_NUM, POSBDCDGCS.POS_TITLE_CD, ALL_POS_CUR_AND_FUT_VW.FUT_SSN_TXT, SITE.STE_ACCREDIT_CD, ALL_POS_CUR_AND_FUT_VW.POS_TITLE_ONE_IND, POSITION_TITLE_DOM.PTLD_EXEMPT_IND, POSBDCDGCS.POS_SAL_SCHD_CD
FROM S1025879.HRMSGCS.ALL_POS_CUR_AND_FUT_VW ALL_POS_CUR_AND_FUT_VW, S1025879.HRMSGCS.POSBDCDGCS POSBDCDGCS, S1025879.HRMSSHR.POSITION_TITLE_DOM POSITION_TITLE_DOM, S1025879.HRMSSHR.SITE SITE
WHERE ALL_POS_CUR_AND_FUT_VW.POS_NUM_CD = POSBDCDGCS.POS_NUM_CD AND ALL_POS_CUR_AND_FUT_VW.POS_SITE_CD = SITE.STE_SITE_CD AND ALL_POS_CUR_AND_FUT_VW.POS_TITLE_CD = POSITION_TITLE_DOM.PTLD_ID AND ((ALL_POS_CUR_AND_FUT_VW.POS_STATUS_CD Between '01' And '51') OR (ALL_POS_CUR_AND_FUT_VW.POS_STATUS_CD='PV'))
ORDER BY ALL_POS_CUR_AND_FUT_VW.POS_SITE_CD, ALL_POS_CUR_AND_FUT_VW.POS_DESC, ALL_POS_CUR_AND_FUT_VW.POS_NUM_CD
    "
      result <- DBI::dbGetQuery(hr_domino, query)
      return(result)
    })
  
  # Execute the requested query
  if (query_name %in% names(queries)) {
    return(queries[[query_name]]())
  } else {
    stop("Invalid query name. Use ComboQueries$ and TAB to see available queries.")
  }
}